import { Deal } from "@/lib/types";

export const mockDeals: Deal[] = [
  {
    id: "deal_bakery_1",
    businessId: "selver_demo",
    businessName: "Selver Demo Store",
    city: "Pärnu",
    address: "Pärnu Keskus",
    title: "Bakery Rescue Bag",
    description: "A mix of fresh bakery items from today. Bread, pastries or sweet buns depending on what is left.",
    category: "bakery",
    price: 3.99,
    originalPrice: 9.5,
    quantityLeft: 4,
    pickupStart: "2026-07-08T18:00:00+03:00",
    pickupEnd: "2026-07-08T19:00:00+03:00",
    status: "available",
  },
  {
    id: "deal_fruit_1",
    businessId: "selver_demo",
    businessName: "Selver Demo Store",
    city: "Pärnu",
    address: "Pärnu Keskus",
    title: "Fruit & Veg Box",
    description: "A practical box of fruit and vegetables that should be used soon. Good for cooking tonight.",
    category: "fruit_veg",
    price: 4.5,
    originalPrice: 11,
    quantityLeft: 2,
    pickupStart: "2026-07-08T17:30:00+03:00",
    pickupEnd: "2026-07-08T20:00:00+03:00",
    status: "available",
  },
  {
    id: "deal_ready_1",
    businessId: "cafe_demo",
    businessName: "Demo Café",
    city: "Tallinn",
    address: "Rotermann",
    title: "Lunch Rescue Pack",
    description: "A ready-to-eat lunch pack from today. Usually includes a salad, wrap, sandwich or warm meal.",
    category: "ready_meal",
    price: 5.99,
    originalPrice: 13.5,
    quantityLeft: 1,
    pickupStart: "2026-07-08T15:00:00+03:00",
    pickupEnd: "2026-07-08T16:30:00+03:00",
    status: "available",
  },
];
